<?php
/**
 * Copyright (c) 2019. IOWEB TECHNOLOGIES
 */

    /**
     * Created by IntelliJ IDEA.
     * User: gabtz
     * Date: 4/7/2019
     * Time: 2:25 PM
     */

    namespace Ioweb\Eurobank\Model\Request;


    use Magento\Payment\Gateway\Command\GatewayCommand;
    use Magento\Payment\Gateway\ErrorMapper\ErrorMessageMapperInterface;
    use Magento\Payment\Gateway\Http\ClientInterface;
    use Magento\Payment\Gateway\Http\TransferFactoryInterface;
    use Magento\Payment\Gateway\Request\BuilderInterface;
    use Magento\Payment\Gateway\Response\HandlerInterface;
    use Magento\Payment\Gateway\Validator\ValidatorInterface;
    use Psr\Log\LoggerInterface;

    class Authorize extends GatewayCommand
    {
        public function __construct(BuilderInterface $requestBuilder, TransferFactoryInterface $transferFactory, ClientInterface $client, LoggerInterface $logger, HandlerInterface $handler = null, ValidatorInterface $validator = null, ?ErrorMessageMapperInterface $errorMessageMapper = null)
        {
            parent::__construct($requestBuilder, $transferFactory, $client, $logger, $handler, $validator, $errorMessageMapper);
        }

        public function execute(array $commandSubject)
        {
            parent::execute($commandSubject); // TODO: Change the autogenerated stub
        }


    }